<<<<<<< HEAD
title: Imran Adamjee's Personal Website
description: This website is primarly here for me to get a job, posted on January 21, 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
theme: jekyll-theme-slate
>>>>>>> 19c0a16b9bdb824273c71ede77bebed74657b0d6
